name = "EfficientModelMatrices"
uuid = "72341345-62c2-4039-9674-a84f8dcc444c"
authors = ["Eric Martin Feltham <eric.feltham@aya.yale.edu>"]
version = "0.1.0"

[deps]
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
StatsModels = "0.7.4"
Tables = "1.12.1"
